### ISSUE TITLE
Ошибочная ссылка на датчики холла

### ISSUE THREAD

**Issue by UndeadMorose** [gotchau/GBot-Tiny-Mark-II#1]
https://github.com/gotchau/GBot-Tiny-Mark-II/blob/0d5c3992c686f5f158b14fd9a77022753a712945/docs/BOM_GBot_Tiny_Mark_II.md?plain=1#L24
В описании ссылка на датчики холла некорректна (равна ссылке на Столик 120х120)

**Comment by gotchau** [comment]
Ссылка исправлена. Спасибо
