### ISSUE TITLE
Old link in BOM (01.02.2023)

### ISSUE THREAD

**Issue by UndeadMorose** [gotchau/GBot-Tiny-Mark-II#2]
Невозможно купить по ссылке | Can't buy from link
https://github.com/gotchau/GBot-Tiny-Mark-II/blob/6027beb782a5f8fa3919d7d40bc652ea41d21398/docs/BOM_GBot_Tiny_Mark_II.md?plain=1#L13
https://github.com/gotchau/GBot-Tiny-Mark-II/blob/6027beb782a5f8fa3919d7d40bc652ea41d21398/docs/BOM_GBot_Tiny_Mark_II.md?plain=1#L23

**Comment by gotchau** [comment]
Ссылки обновлены и на всякий случай продублированы
